### ISSUE TITLE
Can't run in Windows

### ISSUE THREAD

**Issue by matenwego** [rjburdish/ripp-cord-cli#1]
Here's the error I'm seeing:
```
child_process.js:383
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:383:11)
    at exports.spawn (child_process.js:496:38)
    at Object.<anonymous> (C:\Users\Ricardo\AppData\Roaming\npm\node_modules\ripp-cord-cli\bin\cli.js:16:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
```
Here's the current version of npm I'm running `5.6.0`.

Thanks.

**Comment by rjburdish** [comment]
Issue has been resolved with the latest release. Please see v0.1.3
